// Code generated by mockery v2.40.1. DO NOT EDIT.

package mockery

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// transactorMock is an autogenerated mock type for the transactor type
type transactorMock struct {
	mock.Mock
}

// WithinTx provides a mock function with given fields: ctx, fn
func (_m *transactorMock) WithinTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newTransactorMock creates a new instance of transactorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newTransactorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *transactorMock {
	mock := &transactorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
