// Code generated by mockery v2.42.1. DO NOT EDIT.

package mockery

import (
	"context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// mockDbOptSetter is an autogenerated mock type for the dbOptSetter type
type mockDbOptSetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: opt
func (_m *mockDbOptSetter) Execute(opt *sql.TxOptions) {
	_m.Called(opt)
}

// newMockDbOptSetter creates a new instance of mockDbOptSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDbOptSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDbOptSetter {
	mock := &mockDbOptSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRepository is an autogenerated mock type for the repository type
type mockRepository struct {
	mock.Mock
}

// Insert provides a mock function with given fields: ctx, val
func (_m *mockRepository) Insert(ctx context.Context, val string) error {
	ret := _m.Called(ctx, val)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockRepository creates a new instance of mockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRepository {
	mock := &mockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockTransactor is an autogenerated mock type for the transactor type
type mockTransactor struct {
	mock.Mock
}

// WithinTx provides a mock function with given fields: ctx, fn
func (_m *mockTransactor) WithinTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithinTxWithOpts provides a mock function with given fields: ctx, fn, opts
func (_m *mockTransactor) WithinTxWithOpts(ctx context.Context, fn func(context.Context) error, opts ...dbOptSetter) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, fn)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithinTxWithOpts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error, ...dbOptSetter) error); ok {
		r0 = rf(ctx, fn, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockTransactor creates a new instance of mockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTransactor {
	mock := &mockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
