---
project_name: oniontx

builds:
  - skip: true

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  mode: replace