name: Bench

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.26.1

      - name: Bench
        run: |
          cd test/bench
          go test -bench=. -benchmem