name: Integration test

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  workflow_call:

permissions:
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start containers
        run: |
          cd test
          make up.d

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.1

      - name: Show all containers
        run: |
          docker ps -a

      - name: Show all containers logs
        run: |
          cd test
          echo "[ CONTAINERS ]"
          docker compose ls -a
          echo "[ LOGS ]"
          docker compose logs

      - name: Run integration tests
        run: |
          cd test
          go test -v ./... -cover -coverpkg=../... -coverprofile cover.out  && go tool cover -func cover.out

      - name: Stop containers
        if: always()
        run: |
          cd test
          make down
