name: Lint

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  workflow_call:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23.1

      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.7